apiVersion: v1
kind: Namespace
metadata:
  name: sidecar
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sidecar-ingress
  namespace: sidecar
spec:
  rules:
  - host: sidecar.example.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: web-svc
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: sidecar
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/nginx/access.log
      tag nginx.access
      format nginx
    </source>
    <match nginx.access>
      @type stdout
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: vipindevops/blue-green:1.1
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: logging-vol
          mountPath: /var/log/nginx
      - name: fdlogger
        env:
        - name: FLUENT_UID
          value: root
        image: fluent/fluentd:v1.3-debian-1
        volumeMounts:
        - name: logging-vol
          mountPath: /var/log/nginx
        - name: log-config
          mountPath: /fluentd/etc/
      volumes:
          - name: logging-vol
            emptyDir: {}
          - name: log-config
            configMap:
              name: fluentd-config
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: sidecar
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: web